[package]
name = "test_game_rs"
version = "0.1.0"
authors = ["Nicole Mazzuca <nicole@strega-nil.co>"]
edition = "2021"

[dependencies]
agb = "0.18.1"

[profile.dev]
opt-level = 3
debug = true

[profile.release]
opt-level = 3
lto = "fat"
debug = true
